begin;

-- PREPARED ONLY: replaces the adults-only draft. No live application.
-- 18 events, 123 paying adults + 18 guides; invoice/income/cost EUR 4530.
-- First run: 15 changed rows (13 quantities + 2061/1985 pricing).
-- Preserve legacy pax, public/client prices and amounts, payments and invoices.
-- Public amounts and pax require separate review, not automatic correction.
set local lock_timeout = '5s';

do $correction$
declare
  targets constant jsonb := '[
    {"before":{"id":1985,"booking_date":"2026-09-28","booking_reference":"GCAL-_65HJECPK74SJGOB56GQ38P1K6DGMAE1ICGSJ6DR46OP66D1","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":7,"is_cancelled":false,"adults":8,"children":0,"infants":0,"non_paying_adults":1,"total_people":9,"pax":9,"your_unit_price":38,"supplier_unit_cost":38,"public_unit_price":0,"total_to_you":304,"total_supplier_cost":304,"total_customer":0,"total_amount":0,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"after":{"id":1985,"booking_date":"2026-09-28","booking_reference":"GCAL-_65HJECPK74SJGOB56GQ38P1K6DGMAE1ICGSJ6DR46OP66D1","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":7,"is_cancelled":false,"adults":8,"children":0,"infants":0,"non_paying_adults":1,"total_people":9,"pax":9,"your_unit_price":36,"supplier_unit_cost":36,"public_unit_price":0,"total_to_you":288,"total_supplier_cost":288,"total_customer":0,"total_amount":0,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"staging":{"id":534,"gcal_uid":"_65hjecpk74sjgob56gq38p1k6dgmae1icgsj6dr46op66d1o6ss0","booking_date":"2026-09-28","channel_id":7,"original_title":"9 pranzo (1 no glutine no latticini) Tuscan escape","import_status":"needs_review","imported_booking_id":1985}},
    {"before":{"id":2011,"booking_date":"2026-09-14","booking_reference":"GCAL-_60OJ8DJ260QJ6DHG6HH38DHMCCS3ICPH64QM2OHI6LHJ6CP","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":7,"is_cancelled":false,"adults":6,"children":0,"infants":0,"non_paying_adults":1,"total_people":7,"pax":7,"your_unit_price":38,"supplier_unit_cost":38,"public_unit_price":0,"total_to_you":228,"total_supplier_cost":228,"total_customer":0,"total_amount":0,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"after":{"id":2011,"booking_date":"2026-09-14","booking_reference":"GCAL-_60OJ8DJ260QJ6DHG6HH38DHMCCS3ICPH64QM2OHI6LHJ6CP","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":7,"is_cancelled":false,"adults":8,"children":0,"infants":0,"non_paying_adults":1,"total_people":9,"pax":7,"your_unit_price":36,"supplier_unit_cost":36,"public_unit_price":0,"total_to_you":288,"total_supplier_cost":288,"total_customer":0,"total_amount":0,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"staging":{"id":541,"gcal_uid":"_60oj8dj260qj6dhg6hh38dhmccs3icph64qm2ohi6lhj6cpl6tig","booking_date":"2026-09-14","channel_id":7,"original_title":"9 pranzo Tuscan escape","import_status":"ignored","imported_booking_id":null}},
    {"before":{"id":2012,"booking_date":"2026-09-14","booking_reference":"GCAL-_6LH3CC9MCPI36OPK6GR38P9MCDH3EDPO61I3ACHM69J32CB","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":7,"is_cancelled":false,"adults":6,"children":0,"infants":0,"non_paying_adults":1,"total_people":7,"pax":7,"your_unit_price":38,"supplier_unit_cost":38,"public_unit_price":0,"total_to_you":228,"total_supplier_cost":228,"total_customer":0,"total_amount":0,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"after":{"id":2012,"booking_date":"2026-09-14","booking_reference":"GCAL-_6LH3CC9MCPI36OPK6GR38P9MCDH3EDPO61I3ACHM69J32CB","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":7,"is_cancelled":false,"adults":6,"children":0,"infants":0,"non_paying_adults":1,"total_people":7,"pax":7,"your_unit_price":38,"supplier_unit_cost":38,"public_unit_price":0,"total_to_you":228,"total_supplier_cost":228,"total_customer":0,"total_amount":0,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"staging":{"id":542,"gcal_uid":"_6lh3cc9mcpi36opk6gr38p9mcdh3edpo61i3achm69j32cb669i0","booking_date":"2026-09-14","channel_id":7,"original_title":"7 pranzo Tuscan escape","import_status":"ignored","imported_booking_id":null}},
    {"before":{"id":2056,"booking_date":"2026-09-05","booking_reference":"GCAL-_cph30e9jckqj2cpjcop38cb4chh66p33c8pmce9m6ti66c9","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":7,"is_cancelled":false,"adults":4,"children":0,"infants":0,"non_paying_adults":1,"total_people":5,"pax":4,"your_unit_price":38,"supplier_unit_cost":38,"public_unit_price":0,"total_to_you":152,"total_supplier_cost":152,"total_customer":0,"total_amount":0,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"after":{"id":2056,"booking_date":"2026-09-05","booking_reference":"GCAL-_cph30e9jckqj2cpjcop38cb4chh66p33c8pmce9m6ti66c9","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":7,"is_cancelled":false,"adults":4,"children":0,"infants":0,"non_paying_adults":1,"total_people":5,"pax":4,"your_unit_price":38,"supplier_unit_cost":38,"public_unit_price":0,"total_to_you":152,"total_supplier_cost":152,"total_customer":0,"total_amount":0,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"staging":{"id":564,"gcal_uid":"_cph30e9jckqj2cpjcop38cb4chh66p33c8pmce9m6ti66c9h6tj0","booking_date":"2026-09-05","channel_id":7,"original_title":"5 pranzo Tuscan escape","import_status":"imported","imported_booking_id":2056}},
    {"before":{"id":2061,"booking_date":"2026-09-10","booking_reference":"GCAL-_6GOJCOJ360O3GOJ26KP38D32C9GJEP1HC8S6CP1LCKR66D9","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":7,"is_cancelled":false,"adults":8,"children":0,"infants":0,"non_paying_adults":1,"total_people":9,"pax":9,"your_unit_price":38,"supplier_unit_cost":38,"public_unit_price":0,"total_to_you":304,"total_supplier_cost":304,"total_customer":0,"total_amount":0,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"after":{"id":2061,"booking_date":"2026-09-10","booking_reference":"GCAL-_6GOJCOJ360O3GOJ26KP38D32C9GJEP1HC8S6CP1LCKR66D9","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":7,"is_cancelled":false,"adults":8,"children":0,"infants":0,"non_paying_adults":1,"total_people":9,"pax":9,"your_unit_price":36,"supplier_unit_cost":36,"public_unit_price":0,"total_to_you":288,"total_supplier_cost":288,"total_customer":0,"total_amount":0,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"staging":{"id":567,"gcal_uid":"_6gojcoj360o3goj26kp38d32c9gjep1hc8s6cp1lckr66d9n69j0","booking_date":"2026-09-10","channel_id":7,"original_title":"9 pranzo Tuscan escape","import_status":"imported","imported_booking_id":2061}},
    {"before":{"id":2062,"booking_date":"2026-09-08","booking_reference":"GCAL-_CHH64C1I6LIJ0OPNC9H38DHK6TGJCPJ66GS66E1H6SR32O9","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":7,"is_cancelled":false,"adults":7,"children":0,"infants":0,"non_paying_adults":1,"total_people":8,"pax":8,"your_unit_price":38,"supplier_unit_cost":38,"public_unit_price":0,"total_to_you":266,"total_supplier_cost":266,"total_customer":0,"total_amount":0,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"after":{"id":2062,"booking_date":"2026-09-08","booking_reference":"GCAL-_CHH64C1I6LIJ0OPNC9H38DHK6TGJCPJ66GS66E1H6SR32O9","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":7,"is_cancelled":false,"adults":6,"children":0,"infants":0,"non_paying_adults":1,"total_people":7,"pax":8,"your_unit_price":38,"supplier_unit_cost":38,"public_unit_price":0,"total_to_you":228,"total_supplier_cost":228,"total_customer":0,"total_amount":0,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"staging":{"id":566,"gcal_uid":"_chh64c1i6lij0opnc9h38dhk6tgjcpj66gs66e1h6sr32o9j68pg","booking_date":"2026-09-08","channel_id":7,"original_title":"7 pranzo Tuscan escape","import_status":"needs_review","imported_booking_id":2062}},
    {"before":{"id":2063,"booking_date":"2026-09-07","booking_reference":"GCAL-_69H68E1L61GJ6CHI6SP38OHG61GJ2DHN6SR3AC326PGM6D9","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":7,"is_cancelled":false,"adults":6,"children":0,"infants":0,"non_paying_adults":1,"total_people":7,"pax":7,"your_unit_price":38,"supplier_unit_cost":38,"public_unit_price":0,"total_to_you":228,"total_supplier_cost":228,"total_customer":0,"total_amount":0,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"after":{"id":2063,"booking_date":"2026-09-07","booking_reference":"GCAL-_69H68E1L61GJ6CHI6SP38OHG61GJ2DHN6SR3AC326PGM6D9","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":7,"is_cancelled":false,"adults":8,"children":0,"infants":0,"non_paying_adults":1,"total_people":9,"pax":7,"your_unit_price":36,"supplier_unit_cost":36,"public_unit_price":0,"total_to_you":288,"total_supplier_cost":288,"total_customer":0,"total_amount":0,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"staging":{"id":565,"gcal_uid":"_69h68e1l61gj6chi6sp38ohg61gj2dhn6sr3ac326pgm6d9l61ig","booking_date":"2026-09-07","channel_id":7,"original_title":"9 pranzo tuscan escape","import_status":"needs_review","imported_booking_id":2063}},
    {"before":{"id":2073,"booking_date":"2026-09-12","booking_reference":"GCAL-_6TJ68P9GC8SM2C9N6ORJ8D9JCHH3ED1HCOQJICB5CKO64OH","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":22,"is_cancelled":false,"adults":1,"children":0,"infants":0,"non_paying_adults":0,"total_people":1,"pax":1,"your_unit_price":38,"supplier_unit_cost":38,"public_unit_price":45,"total_to_you":38,"total_supplier_cost":38,"total_customer":45,"total_amount":45,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"after":{"id":2073,"booking_date":"2026-09-12","booking_reference":"GCAL-_6TJ68P9GC8SM2C9N6ORJ8D9JCHH3ED1HCOQJICB5CKO64OH","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":22,"is_cancelled":false,"adults":8,"children":0,"infants":0,"non_paying_adults":1,"total_people":9,"pax":1,"your_unit_price":36,"supplier_unit_cost":36,"public_unit_price":45,"total_to_you":288,"total_supplier_cost":288,"total_customer":45,"total_amount":45,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"staging":{"id":576,"gcal_uid":"_6tj68p9gc8sm2c9n6orj8d9jchh3ed1hcoqjicb5cko64ohj6dgg","booking_date":"2026-09-12","channel_id":7,"original_title":"9 pranzo Tuscan escape","import_status":"needs_review","imported_booking_id":2073}},
    {"before":{"id":2074,"booking_date":"2026-09-18","booking_reference":"GCAL-_C9H34E1MCOS66D1H64R38E1N70SJ4OPJC4S3GD1P65J30EB","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":22,"is_cancelled":false,"adults":1,"children":0,"infants":0,"non_paying_adults":0,"total_people":1,"pax":1,"your_unit_price":38,"supplier_unit_cost":38,"public_unit_price":45,"total_to_you":38,"total_supplier_cost":38,"total_customer":45,"total_amount":45,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"after":{"id":2074,"booking_date":"2026-09-18","booking_reference":"GCAL-_C9H34E1MCOS66D1H64R38E1N70SJ4OPJC4S3GD1P65J30EB","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":22,"is_cancelled":false,"adults":8,"children":0,"infants":0,"non_paying_adults":1,"total_people":9,"pax":1,"your_unit_price":36,"supplier_unit_cost":36,"public_unit_price":45,"total_to_you":288,"total_supplier_cost":288,"total_customer":45,"total_amount":45,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"staging":{"id":578,"gcal_uid":"_c9h34e1mcos66d1h64r38e1n70sj4opjc4s3gd1p65j30eb3cksg","booking_date":"2026-09-18","channel_id":7,"original_title":"9 pranzo Tuscan escape","import_status":"ignored","imported_booking_id":null}},
    {"before":{"id":2075,"booking_date":"2026-09-17","booking_reference":"GCAL-_64O3GE9M6PHM8OR26LH38DHJCGS3IPB16SQ38C9LC4O66PB","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":22,"is_cancelled":false,"adults":1,"children":0,"infants":0,"non_paying_adults":0,"total_people":1,"pax":1,"your_unit_price":38,"supplier_unit_cost":38,"public_unit_price":45,"total_to_you":38,"total_supplier_cost":38,"total_customer":45,"total_amount":45,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"after":{"id":2075,"booking_date":"2026-09-17","booking_reference":"GCAL-_64O3GE9M6PHM8OR26LH38DHJCGS3IPB16SQ38C9LC4O66PB","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":22,"is_cancelled":false,"adults":5,"children":0,"infants":0,"non_paying_adults":1,"total_people":6,"pax":1,"your_unit_price":38,"supplier_unit_cost":38,"public_unit_price":45,"total_to_you":190,"total_supplier_cost":190,"total_customer":45,"total_amount":45,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"staging":{"id":577,"gcal_uid":"_64o3ge9m6phm8or26lh38dhjcgs3ipb16sq38c9lc4o66pb3c8og","booking_date":"2026-09-17","channel_id":7,"original_title":"6 pranzo Tuscan escape","import_status":"needs_review","imported_booking_id":2075}},
    {"before":{"id":2078,"booking_date":"2026-09-27","booking_reference":"GCAL-_CLHJEP1L6TI6COHL61I38DHN69GJAE1P68SMAE1H64O64C1","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":22,"is_cancelled":false,"adults":1,"children":0,"infants":0,"non_paying_adults":0,"total_people":1,"pax":1,"your_unit_price":38,"supplier_unit_cost":38,"public_unit_price":45,"total_to_you":38,"total_supplier_cost":38,"total_customer":45,"total_amount":45,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"after":{"id":2078,"booking_date":"2026-09-27","booking_reference":"GCAL-_CLHJEP1L6TI6COHL61I38DHN69GJAE1P68SMAE1H64O64C1","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":22,"is_cancelled":false,"adults":4,"children":0,"infants":0,"non_paying_adults":1,"total_people":5,"pax":1,"your_unit_price":38,"supplier_unit_cost":38,"public_unit_price":45,"total_to_you":152,"total_supplier_cost":152,"total_customer":45,"total_amount":45,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"staging":{"id":585,"gcal_uid":"_clhjep1l6ti6cohl61i38dhn69gjae1p68smae1h64o64c1m6hhg","booking_date":"2026-09-27","channel_id":7,"original_title":"5 pranzo Tuscan escape","import_status":"needs_review","imported_booking_id":2078}},
    {"before":{"id":2079,"booking_date":"2026-09-26","booking_reference":"GCAL-_68SJ6D1P6KR3GE3471J38O9NCLH64P9NC8QJ4OJ460O3AC9","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":22,"is_cancelled":false,"adults":7,"children":0,"infants":0,"non_paying_adults":1,"total_people":8,"pax":8,"your_unit_price":38,"supplier_unit_cost":38,"public_unit_price":45,"total_to_you":266,"total_supplier_cost":266,"total_customer":315,"total_amount":315,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"after":{"id":2079,"booking_date":"2026-09-26","booking_reference":"GCAL-_68SJ6D1P6KR3GE3471J38O9NCLH64P9NC8QJ4OJ460O3AC9","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":22,"is_cancelled":false,"adults":7,"children":0,"infants":0,"non_paying_adults":1,"total_people":8,"pax":8,"your_unit_price":38,"supplier_unit_cost":38,"public_unit_price":45,"total_to_you":266,"total_supplier_cost":266,"total_customer":315,"total_amount":315,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"staging":{"id":584,"gcal_uid":"_68sj6d1p6kr3ge3471j38o9nclh64p9nc8qj4oj460o3ac9mcks0","booking_date":"2026-09-26","channel_id":7,"original_title":"8 pranzo Tuscan escape","import_status":"needs_review","imported_booking_id":2079}},
    {"before":{"id":2080,"booking_date":"2026-09-24","booking_reference":"GCAL-_CKQJ0CPOCLJ3IC1ICHIJ8D1O69H32PB1C4OJ0E3264PJEDH","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":22,"is_cancelled":false,"adults":1,"children":0,"infants":0,"non_paying_adults":0,"total_people":1,"pax":1,"your_unit_price":38,"supplier_unit_cost":38,"public_unit_price":45,"total_to_you":38,"total_supplier_cost":38,"total_customer":45,"total_amount":45,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"after":{"id":2080,"booking_date":"2026-09-24","booking_reference":"GCAL-_CKQJ0CPOCLJ3IC1ICHIJ8D1O69H32PB1C4OJ0E3264PJEDH","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":22,"is_cancelled":false,"adults":8,"children":0,"infants":0,"non_paying_adults":1,"total_people":9,"pax":1,"your_unit_price":36,"supplier_unit_cost":36,"public_unit_price":45,"total_to_you":288,"total_supplier_cost":288,"total_customer":45,"total_amount":45,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"staging":{"id":583,"gcal_uid":"_ckqj0cpoclj3ic1ichij8d1o69h32pb1c4oj0e3264pjedho70p0","booking_date":"2026-09-24","channel_id":7,"original_title":"9 pranzo Tuscan escape","import_status":"ignored","imported_booking_id":null}},
    {"before":{"id":2081,"booking_date":"2026-09-22","booking_reference":"GCAL-_CGOJIE9M6LJ6AEB36GR38E9P61H32CHGC8RJ2E1NC8S3CCP","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":22,"is_cancelled":false,"adults":1,"children":0,"infants":0,"non_paying_adults":0,"total_people":1,"pax":1,"your_unit_price":38,"supplier_unit_cost":38,"public_unit_price":45,"total_to_you":38,"total_supplier_cost":38,"total_customer":45,"total_amount":45,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"after":{"id":2081,"booking_date":"2026-09-22","booking_reference":"GCAL-_CGOJIE9M6LJ6AEB36GR38E9P61H32CHGC8RJ2E1NC8S3CCP","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":22,"is_cancelled":false,"adults":8,"children":0,"infants":0,"non_paying_adults":1,"total_people":9,"pax":1,"your_unit_price":36,"supplier_unit_cost":36,"public_unit_price":45,"total_to_you":288,"total_supplier_cost":288,"total_customer":45,"total_amount":45,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"staging":{"id":582,"gcal_uid":"_cgojie9m6lj6aeb36gr38e9p61h32chgc8rj2e1nc8s3ccpj6pig","booking_date":"2026-09-22","channel_id":7,"original_title":"9 pranzo Tuscan escape","import_status":"needs_review","imported_booking_id":2081}},
    {"before":{"id":2082,"booking_date":"2026-09-21","booking_reference":"GCAL-_68Q3IDHO70SJ2P9JC4RJ8CPG70S3CDHL6GPMCCHI60O3EP3","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":22,"is_cancelled":false,"adults":1,"children":0,"infants":0,"non_paying_adults":0,"total_people":1,"pax":1,"your_unit_price":38,"supplier_unit_cost":38,"public_unit_price":45,"total_to_you":38,"total_supplier_cost":38,"total_customer":45,"total_amount":45,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"after":{"id":2082,"booking_date":"2026-09-21","booking_reference":"GCAL-_68Q3IDHO70SJ2P9JC4RJ8CPG70S3CDHL6GPMCCHI60O3EP3","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":22,"is_cancelled":false,"adults":8,"children":0,"infants":0,"non_paying_adults":1,"total_people":9,"pax":1,"your_unit_price":36,"supplier_unit_cost":36,"public_unit_price":45,"total_to_you":288,"total_supplier_cost":288,"total_customer":45,"total_amount":45,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"staging":{"id":581,"gcal_uid":"_68q3idho70sj2p9jc4rj8cpg70s3cdhl6gpmcchi60o3ep366gp0","booking_date":"2026-09-21","channel_id":7,"original_title":"9 pranzo Tuscan escape","import_status":"needs_review","imported_booking_id":2082}},
    {"before":{"id":2115,"booking_date":"2026-09-15","booking_reference":"GCAL-_C4SM2OJ2CLHJECHJ71GJ8DJ5CKS3GO9M6CS34PB569HJIOP","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":7,"is_cancelled":false,"adults":8,"children":0,"infants":0,"non_paying_adults":1,"total_people":9,"pax":9,"your_unit_price":38,"supplier_unit_cost":38,"public_unit_price":0,"total_to_you":304,"total_supplier_cost":304,"total_customer":0,"total_amount":0,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"after":{"id":2115,"booking_date":"2026-09-15","booking_reference":"GCAL-_C4SM2OJ2CLHJECHJ71GJ8DJ5CKS3GO9M6CS34PB569HJIOP","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":7,"is_cancelled":false,"adults":7,"children":0,"infants":0,"non_paying_adults":1,"total_people":8,"pax":9,"your_unit_price":38,"supplier_unit_cost":38,"public_unit_price":0,"total_to_you":266,"total_supplier_cost":266,"total_customer":0,"total_amount":0,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"staging":{"id":598,"gcal_uid":"_c4sm2oj2clhjechj71gj8dj5cks3go9m6cs34pb569hjiopp6kpg","booking_date":"2026-09-15","channel_id":7,"original_title":"8 pranzo Tuscan escape","import_status":"needs_review","imported_booking_id":2115}},
    {"before":{"id":2146,"booking_date":"2026-09-20","booking_reference":"GCAL-_6lh66e1g6opmae9hcor38phkc9gj2opn6him2d1icosjap3","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":22,"is_cancelled":false,"adults":1,"children":0,"infants":0,"non_paying_adults":0,"total_people":1,"pax":1,"your_unit_price":0,"supplier_unit_cost":0,"public_unit_price":0,"total_to_you":0,"total_supplier_cost":0,"total_customer":0,"total_amount":0,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"after":{"id":2146,"booking_date":"2026-09-20","booking_reference":"GCAL-_6lh66e1g6opmae9hcor38phkc9gj2opn6him2d1icosjap3","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":22,"is_cancelled":false,"adults":5,"children":0,"infants":0,"non_paying_adults":1,"total_people":6,"pax":1,"your_unit_price":38,"supplier_unit_cost":38,"public_unit_price":0,"total_to_you":190,"total_supplier_cost":190,"total_customer":0,"total_amount":0,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"staging":{"id":620,"gcal_uid":"_6lh66e1g6opmae9hcor38phkc9gj2opn6him2d1icosjap326opg","booking_date":"2026-09-20","channel_id":7,"original_title":"6 pranzo Tuscan escape","import_status":"needs_review","imported_booking_id":2146}},
    {"before":{"id":2227,"booking_date":"2026-09-29","booking_reference":"GCAL-_70s36php74o3ec1i6cp38ob465gm8opkchj68d9gckp3ccr","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":22,"is_cancelled":false,"adults":1,"children":0,"infants":0,"non_paying_adults":0,"total_people":1,"pax":1,"your_unit_price":0,"supplier_unit_cost":0,"public_unit_price":0,"total_to_you":0,"total_supplier_cost":0,"total_customer":0,"total_amount":0,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"after":{"id":2227,"booking_date":"2026-09-29","booking_reference":"GCAL-_70s36php74o3ec1i6cp38ob465gm8opkchj68d9gckp3ccr","channel_id":7,"business_unit_id":1,"supplier_id":3,"experience_id":22,"is_cancelled":false,"adults":7,"children":0,"infants":0,"non_paying_adults":1,"total_people":8,"pax":1,"your_unit_price":38,"supplier_unit_cost":38,"public_unit_price":0,"total_to_you":266,"total_supplier_cost":266,"total_customer":0,"total_amount":0,"margin_total":0,"agreed_unit_price":null,"total_to_you_source":null,"supplier_amount_paid":0,"customer_payment_status":"pending","supplier_payment_status":"pending"},"staging":{"id":656,"gcal_uid":"_70s36php74o3ec1i6cp38ob465gm8opkchj68d9gckp3ccr16gog","booking_date":"2026-09-29","channel_id":7,"original_title":"8 pranzo Tuscan escape","import_status":"needs_review","imported_booking_id":2227}}
  ]'::jsonb;
  target jsonb;
  snapshot jsonb := '{}'::jsonb;
  current_row jsonb;
  expected_after jsonb;
  affected integer;
begin
  perform b.id from public.bookings b
  where b.id in (select (t->'before'->>'id')::bigint from jsonb_array_elements(targets) t)
  order by b.id for update;

  -- Unknown UPDATE hooks could modify timestamps, totals or other tables.
  if exists (
    select 1 from pg_trigger where tgrelid = 'public.bookings'::regclass
      and not tgisinternal and tgenabled <> 'D' and (tgtype::integer & 16) <> 0
  ) or exists (
    select 1 from pg_rewrite where ev_class = 'public.bookings'::regclass
      and ev_type = '2' and ev_enabled <> 'D'
  ) then
    raise exception 'Tuscan correction: bookings UPDATE triggers/rules require prior review';
  end if;

  -- Read-only source guards: retain source evidence throughout the transaction.
  perform s.id from public.google_calendar_import_staging s
  where s.id in (select (t->'staging'->>'id')::bigint from jsonb_array_elements(targets) t)
  order by s.id for share;

  -- Complete preflight before the first write. Accept the entire original or
  -- entire final state, not mixed fields potentially resulting from manual edits.
  for target in select value from jsonb_array_elements(targets)
  loop
    select to_jsonb(b) into current_row from public.bookings b
    where b.id = (target->'before'->>'id')::bigint;
    if not found or not (current_row @> (target->'before') or current_row @> (target->'after')) then
      raise exception 'Tuscan correction: ID % missing or guards differ', target->'before'->>'id';
    end if;
    if not exists (
      select 1 from public.google_calendar_import_staging s
      where s.id = (target->'staging'->>'id')::bigint and to_jsonb(s) @> (target->'staging')
    ) then
      raise exception 'Tuscan correction: source evidence changed for booking %', target->'before'->>'id';
    end if;
    snapshot := snapshot || jsonb_build_object(target->'before'->>'id', current_row);
  end loop;

  for target in select value from jsonb_array_elements(targets)
  loop
    expected_after := target->'after';
    if (snapshot->(target->'before'->>'id')) @> expected_after then continue; end if;
    update public.bookings b set
      adults = (expected_after->>'adults')::integer,
      non_paying_adults = (expected_after->>'non_paying_adults')::integer,
      total_people = (expected_after->>'total_people')::integer,
      your_unit_price = (expected_after->>'your_unit_price')::numeric,
      supplier_unit_cost = (expected_after->>'supplier_unit_cost')::numeric,
      total_to_you = (expected_after->>'total_to_you')::numeric,
      total_supplier_cost = (expected_after->>'total_supplier_cost')::numeric,
      margin_total = (expected_after->>'margin_total')::numeric
    where b.id = (expected_after->>'id')::bigint and to_jsonb(b) @> (target->'before');
    get diagnostics affected = row_count;
    if affected <> 1 then
      raise exception 'Tuscan correction: ID % expected exactly one UPDATE', expected_after->>'id';
    end if;
  end loop;

  for target in select value from jsonb_array_elements(targets)
  loop
    expected_after := target->'after';
    select to_jsonb(b) into current_row from public.bookings b where b.id = (expected_after->>'id')::bigint;
    if not found or not current_row @> expected_after
      or (current_row - array['adults','non_paying_adults','total_people','your_unit_price','supplier_unit_cost','total_to_you','total_supplier_cost','margin_total'])
        is distinct from
        ((snapshot->(expected_after->>'id')) - array['adults','non_paying_adults','total_people','your_unit_price','supplier_unit_cost','total_to_you','total_supplier_cost','margin_total']) then
      raise exception 'Tuscan correction: ID % postcondition failed', expected_after->>'id';
    end if;
  end loop;
end;
$correction$;

commit;
