-- PREPARED ONLY: six October 2026 Tuscan Escape bookings. DO NOT APPLY WITHOUT APPROVAL.
-- Google Calendar read_event verified all six confirmed, titles/date/time/UID on 2026-10-09.
-- Connector does NOT expose Google updated: never mark legacy chronology verified.
-- Recheck Google before future execution; SQL cannot contact Calendar.
-- Economics remain byte-for-byte unchanged (zero); all six need separate financial review.
-- Booking manual flag / canonical manual-review marker protect this reviewed repair.
-- Canonical 1322 is already correct and is retained entirely.
-- Staging remains needs_review, including structured anomaly 612, pending financial/source review.
-- Blocks 2140,2138,2137,2292 and all September/May/other-channel rows are excluded.
begin;
set local lock_timeout = '5s';
do $correction$
declare
  targets jsonb := '[
  {
    "before": {
      "id": 2145,
      "customer_name": "Tuscan Escape",
      "experience_name": "Tuscan Escape - Blocco data",
      "booking_date": "2026-10-01",
      "pax": 1,
      "total_amount": 0,
      "customer_payment_status": "pending",
      "supplier_payment_status": "pending",
      "created_at": "2026-09-14T18:18:53.449768+00:00",
      "booking_source": "Tuscan Escape",
      "booking_reference": "GCAL-_c4ojadpo69j3gopichh38p1j75gmadj668oj0o9k6hgj4e9",
      "booking_created_at": "2026-09-14",
      "booking_time": "13:15",
      "adults": 1,
      "children": 0,
      "total_people": 1,
      "customer_phone": null,
      "customer_email": null,
      "notes": "Tuscan escape",
      "channel_id": 7,
      "experience_id": 22,
      "supplier_id": 3,
      "your_unit_price": 0,
      "public_unit_price": 0,
      "supplier_unit_cost": 0,
      "total_to_you": 0,
      "total_customer": 0,
      "total_supplier_cost": 0,
      "margin_total": 0,
      "is_cancelled": false,
      "cancelled_at": null,
      "supplier_amount_paid": 0,
      "infants": 0,
      "updated_at": "2026-09-14T18:18:53.449768+00:00",
      "was_modified": false,
      "recovery_tag": null,
      "business_unit_id": 1,
      "non_paying_adults": 0,
      "bokun_booking_reference": null,
      "total_to_you_source": null,
      "agreed_unit_price": null
    },
    "after": {
      "id": 2145,
      "customer_name": "Tuscan Escape",
      "experience_name": "Tour della Cinta Senese con pranzo",
      "booking_date": "2026-10-01",
      "pax": 8,
      "total_amount": 0,
      "customer_payment_status": "pending",
      "supplier_payment_status": "pending",
      "created_at": "2026-09-14T18:18:53.449768+00:00",
      "booking_source": "Tuscan Escape",
      "booking_reference": "GCAL-_c4ojadpo69j3gopichh38p1j75gmadj668oj0o9k6hgj4e9",
      "booking_created_at": "2026-09-14",
      "booking_time": "13:15",
      "adults": 8,
      "children": 0,
      "total_people": 9,
      "customer_phone": null,
      "customer_email": null,
      "notes": "9 pranzo Tuscan escape",
      "channel_id": 7,
      "experience_id": 7,
      "supplier_id": 3,
      "your_unit_price": 0,
      "public_unit_price": 0,
      "supplier_unit_cost": 0,
      "total_to_you": 0,
      "total_customer": 0,
      "total_supplier_cost": 0,
      "margin_total": 0,
      "is_cancelled": false,
      "cancelled_at": null,
      "supplier_amount_paid": 0,
      "infants": 0,
      "updated_at": "2026-09-14T18:18:53.449768+00:00",
      "was_modified": true,
      "recovery_tag": null,
      "business_unit_id": 1,
      "non_paying_adults": 1,
      "bokun_booking_reference": null,
      "total_to_you_source": null,
      "agreed_unit_price": null
    },
    "staging": {
      "id": 612,
      "booking_date": "2026-10-01",
      "booking_time": "13:15:00",
      "booking_reference": "GCAL-_c4ojadpo69j3gopichh38p1j75gmadj668oj0o9k6hgj4e9",
      "customer_name": "Tuscan Escape",
      "adults": 1,
      "children": 0,
      "infants": 0,
      "experience_id": 22,
      "channel_id": 7,
      "booking_source": "Tuscan Escape",
      "notes": "9 pranzo Tuscan escape",
      "gcal_uid": "_c4ojadpo69j3gopichh38p1j75gmadj668oj0o9k6hgj4e9jc4q0",
      "original_title": "9 pranzo Tuscan escape",
      "import_status": "needs_review",
      "imported_booking_id": 2145,
      "created_at": "2026-09-14T16:13:39.432324+00:00",
      "import_origin": "make",
      "gcal_updated_at": "2026-09-27T06:01:11+00:00",
      "gcal_html_link": "https://www.google.com/calendar/event?eid=X2M0b2phZHBvNjlqM2dvcGljaGgzOHAxajc1Z21hZGo2NjhvajBvOWs2aGdqNGU5amM0cTAgY2FsZW5kYXJpby5mYXR0b3JpYUBt"
    },
    "canonical_before": {
      "id": 1291,
      "calendar_id": null,
      "identity_namespace": "legacy_unscoped",
      "canonical_uid": "a15782f8c2db4d39ae6f210a44a293a4",
      "original_uid": "_c4ojadpo69j3gopichh38p1j75gmadj668oj0o9k6hgj4e9jc4q0",
      "uid_kind": "google",
      "uid_semantics": "legacy_unknown",
      "occurrence_id": null,
      "gcal_event_id": null,
      "gcal_ical_uid": null,
      "recurring_event_id": null,
      "original_start_at": null,
      "original_start_date": null,
      "original_start_timezone": null,
      "event_date": "2026-10-01",
      "event_time": "13:15:00",
      "original_title": "Tuscan escape",
      "gcal_html_link": "https://www.google.com/calendar/event?eid=X2M0b2phZHBvNjlqM2dvcGljaGgzOHAxajc1Z21hZGo2NjhvajBvOWs2aGdqNGU5amM0cTAgY2FsZW5kYXJpby5mYXR0b3JpYUBt",
      "gcal_event_status": "unknown",
      "gcal_updated_at": "2026-09-14T16:03:17+00:00",
      "gcal_received_at": null,
      "historical_booking_id": null,
      "staging_id": 612,
      "historical_source": null,
      "historical_snapshot_at": null,
      "historical_total_guests": null,
      "observed_total_guests": null,
      "effective_total_guests": null,
      "attendance_source": "unknown",
      "attendance_quality": "unknown",
      "attendance_parser_version": "gcal-attendance-review-v1",
      "event_classification": "operational_block",
      "exclusion_reason": "explicit_tuscan_escape_block",
      "last_observation_source": "google_calendar",
      "created_at": "2026-09-17T20:44:04.270063+00:00",
      "updated_at": "2026-09-17T20:44:04.270063+00:00",
      "gcal_observation_verified": false
    },
    "canonical_after": {
      "id": 1291,
      "calendar_id": null,
      "identity_namespace": "legacy_unscoped",
      "canonical_uid": "a15782f8c2db4d39ae6f210a44a293a4",
      "original_uid": "_c4ojadpo69j3gopichh38p1j75gmadj668oj0o9k6hgj4e9jc4q0",
      "uid_kind": "google",
      "uid_semantics": "legacy_unknown",
      "occurrence_id": null,
      "gcal_event_id": null,
      "gcal_ical_uid": null,
      "recurring_event_id": null,
      "original_start_at": null,
      "original_start_date": null,
      "original_start_timezone": null,
      "event_date": "2026-10-01",
      "event_time": "13:15:00",
      "original_title": "9 pranzo Tuscan escape",
      "gcal_html_link": "https://www.google.com/calendar/event?eid=X2M0b2phZHBvNjlqM2dvcGljaGgzOHAxajc1Z21hZGo2NjhvajBvOWs2aGdqNGU5amM0cTAgY2FsZW5kYXJpby5mYXR0b3JpYUBt",
      "gcal_event_status": "confirmed",
      "gcal_updated_at": "2026-09-14T16:03:17+00:00",
      "gcal_received_at": null,
      "historical_booking_id": null,
      "staging_id": 612,
      "historical_source": null,
      "historical_snapshot_at": null,
      "historical_total_guests": null,
      "observed_total_guests": 9,
      "effective_total_guests": 8,
      "attendance_source": "google_title",
      "attendance_quality": "parsed",
      "attendance_parser_version": "farm-attendance-v1+manual-review-20261009",
      "event_classification": "customer_event",
      "exclusion_reason": null,
      "last_observation_source": "google_calendar",
      "created_at": "2026-09-17T20:44:04.270063+00:00",
      "updated_at": "2026-09-17T20:44:04.270063+00:00",
      "gcal_observation_verified": false
    },
    "aliases": [
      {
        "id": 1677,
        "event_id": 1291,
        "calendar_id": null,
        "identity_namespace": "legacy_unscoped",
        "occurrence_id": null,
        "original_uid": "_c4ojadpo69j3gopichh38p1j75gmadj668oj0o9k6hgj4e9jc4q0",
        "canonical_uid": "a15782f8c2db4d39ae6f210a44a293a4",
        "alias_type": "base32hex",
        "reconciliation_method": "base32hex_roundtrip",
        "verified": true,
        "historical_booking_id": null,
        "created_at": "2026-09-17T20:44:04.270063+00:00"
      },
      {
        "id": 1678,
        "event_id": 1291,
        "calendar_id": null,
        "identity_namespace": "legacy_unscoped",
        "occurrence_id": null,
        "original_uid": "a15782f8c2db4d39ae6f210a44a293a4",
        "canonical_uid": "a15782f8c2db4d39ae6f210a44a293a4",
        "alias_type": "google_uid",
        "reconciliation_method": "identity",
        "verified": true,
        "historical_booking_id": null,
        "created_at": "2026-09-17T20:44:04.270063+00:00"
      }
    ],
    "google_evidence": {
      "id": "_c4ojadpo69j3gopichh38p1j75gmadj668oj0o9k6hgj4e9jc4q0",
      "summary": "9 pranzo Tuscan escape",
      "status": "confirmed",
      "start": "2026-10-01T13:15:00+02:00",
      "recurring_event_id": null,
      "original_start_time": null,
      "organizer": "calendario.fattoria@gmail.com"
    }
  },
  {
    "before": {
      "id": 2144,
      "customer_name": "Tuscan Escape",
      "experience_name": "Tuscan Escape - Blocco data",
      "booking_date": "2026-10-05",
      "pax": 1,
      "total_amount": 0,
      "customer_payment_status": "pending",
      "supplier_payment_status": "pending",
      "created_at": "2026-09-14T18:18:39.735224+00:00",
      "booking_source": "Tuscan Escape",
      "booking_reference": "GCAL-_cor36ohn6kq68or5clh38oj675h3id366crm6db571j38cr",
      "booking_created_at": "2026-09-14",
      "booking_time": "13:15",
      "adults": 1,
      "children": 0,
      "total_people": 1,
      "customer_phone": null,
      "customer_email": null,
      "notes": "Tuscan escape",
      "channel_id": 7,
      "experience_id": 22,
      "supplier_id": 3,
      "your_unit_price": 0,
      "public_unit_price": 0,
      "supplier_unit_cost": 0,
      "total_to_you": 0,
      "total_customer": 0,
      "total_supplier_cost": 0,
      "margin_total": 0,
      "is_cancelled": false,
      "cancelled_at": null,
      "supplier_amount_paid": 0,
      "infants": 0,
      "updated_at": "2026-09-14T18:18:39.735224+00:00",
      "was_modified": false,
      "recovery_tag": null,
      "business_unit_id": 1,
      "non_paying_adults": 0,
      "bokun_booking_reference": null,
      "total_to_you_source": null,
      "agreed_unit_price": null
    },
    "after": {
      "id": 2144,
      "customer_name": "Tuscan Escape",
      "experience_name": "Tour della Cinta Senese con pranzo",
      "booking_date": "2026-10-05",
      "pax": 8,
      "total_amount": 0,
      "customer_payment_status": "pending",
      "supplier_payment_status": "pending",
      "created_at": "2026-09-14T18:18:39.735224+00:00",
      "booking_source": "Tuscan Escape",
      "booking_reference": "GCAL-_cor36ohn6kq68or5clh38oj675h3id366crm6db571j38cr",
      "booking_created_at": "2026-09-14",
      "booking_time": "13:15",
      "adults": 8,
      "children": 0,
      "total_people": 9,
      "customer_phone": null,
      "customer_email": null,
      "notes": "9 pranzo Tuscan escape",
      "channel_id": 7,
      "experience_id": 7,
      "supplier_id": 3,
      "your_unit_price": 0,
      "public_unit_price": 0,
      "supplier_unit_cost": 0,
      "total_to_you": 0,
      "total_customer": 0,
      "total_supplier_cost": 0,
      "margin_total": 0,
      "is_cancelled": false,
      "cancelled_at": null,
      "supplier_amount_paid": 0,
      "infants": 0,
      "updated_at": "2026-09-14T18:18:39.735224+00:00",
      "was_modified": true,
      "recovery_tag": null,
      "business_unit_id": 1,
      "non_paying_adults": 1,
      "bokun_booking_reference": null,
      "total_to_you_source": null,
      "agreed_unit_price": null
    },
    "staging": {
      "id": 613,
      "booking_date": "2026-10-05",
      "booking_time": "13:15:00",
      "booking_reference": "GCAL-_cor36ohn6kq68or5clh38oj675h3id366crm6db571j38cr",
      "customer_name": "Tuscan",
      "adults": 8,
      "children": 0,
      "infants": 0,
      "experience_id": 7,
      "channel_id": 7,
      "booking_source": "Tuscan Escape",
      "notes": "9 pranzo Tuscan escape",
      "gcal_uid": "_cor36ohn6kq68or5clh38oj675h3id366crm6db571j38cr1c4og",
      "original_title": "9 pranzo Tuscan escape",
      "import_status": "needs_review",
      "imported_booking_id": 2144,
      "created_at": "2026-09-14T16:13:40.744005+00:00",
      "import_origin": "make",
      "gcal_updated_at": "2026-10-03T18:16:40+00:00",
      "gcal_html_link": "https://www.google.com/calendar/event?eid=X2NvcjM2b2huNmtxNjhvcjVjbGgzOG9qNjc1aDNpZDM2NmNybTZkYjU3MWozOGNyMWM0b2cgY2FsZW5kYXJpby5mYXR0b3JpYUBt"
    },
    "canonical_before": {
      "id": 1292,
      "calendar_id": null,
      "identity_namespace": "legacy_unscoped",
      "canonical_uid": "f63b754dceeb4bf9b94f37c5e8f43aa1",
      "original_uid": "_cor36ohn6kq68or5clh38oj675h3id366crm6db571j38cr1c4og",
      "uid_kind": "google",
      "uid_semantics": "legacy_unknown",
      "occurrence_id": null,
      "gcal_event_id": null,
      "gcal_ical_uid": null,
      "recurring_event_id": null,
      "original_start_at": null,
      "original_start_date": null,
      "original_start_timezone": null,
      "event_date": "2026-10-05",
      "event_time": "13:15:00",
      "original_title": "Tuscan escape",
      "gcal_html_link": "https://www.google.com/calendar/event?eid=X2NvcjM2b2huNmtxNjhvcjVjbGgzOG9qNjc1aDNpZDM2NmNybTZkYjU3MWozOGNyMWM0b2cgY2FsZW5kYXJpby5mYXR0b3JpYUBt",
      "gcal_event_status": "unknown",
      "gcal_updated_at": "2026-09-14T16:03:29+00:00",
      "gcal_received_at": null,
      "historical_booking_id": null,
      "staging_id": 613,
      "historical_source": null,
      "historical_snapshot_at": null,
      "historical_total_guests": null,
      "observed_total_guests": null,
      "effective_total_guests": null,
      "attendance_source": "unknown",
      "attendance_quality": "unknown",
      "attendance_parser_version": "gcal-attendance-review-v1",
      "event_classification": "operational_block",
      "exclusion_reason": "explicit_tuscan_escape_block",
      "last_observation_source": "google_calendar",
      "created_at": "2026-09-17T20:44:04.270063+00:00",
      "updated_at": "2026-09-17T20:44:04.270063+00:00",
      "gcal_observation_verified": false
    },
    "canonical_after": {
      "id": 1292,
      "calendar_id": null,
      "identity_namespace": "legacy_unscoped",
      "canonical_uid": "f63b754dceeb4bf9b94f37c5e8f43aa1",
      "original_uid": "_cor36ohn6kq68or5clh38oj675h3id366crm6db571j38cr1c4og",
      "uid_kind": "google",
      "uid_semantics": "legacy_unknown",
      "occurrence_id": null,
      "gcal_event_id": null,
      "gcal_ical_uid": null,
      "recurring_event_id": null,
      "original_start_at": null,
      "original_start_date": null,
      "original_start_timezone": null,
      "event_date": "2026-10-05",
      "event_time": "13:15:00",
      "original_title": "9 pranzo Tuscan escape",
      "gcal_html_link": "https://www.google.com/calendar/event?eid=X2NvcjM2b2huNmtxNjhvcjVjbGgzOG9qNjc1aDNpZDM2NmNybTZkYjU3MWozOGNyMWM0b2cgY2FsZW5kYXJpby5mYXR0b3JpYUBt",
      "gcal_event_status": "confirmed",
      "gcal_updated_at": "2026-09-14T16:03:29+00:00",
      "gcal_received_at": null,
      "historical_booking_id": null,
      "staging_id": 613,
      "historical_source": null,
      "historical_snapshot_at": null,
      "historical_total_guests": null,
      "observed_total_guests": 9,
      "effective_total_guests": 8,
      "attendance_source": "google_title",
      "attendance_quality": "parsed",
      "attendance_parser_version": "farm-attendance-v1+manual-review-20261009",
      "event_classification": "customer_event",
      "exclusion_reason": null,
      "last_observation_source": "google_calendar",
      "created_at": "2026-09-17T20:44:04.270063+00:00",
      "updated_at": "2026-09-17T20:44:04.270063+00:00",
      "gcal_observation_verified": false
    },
    "aliases": [
      {
        "id": 1679,
        "event_id": 1292,
        "calendar_id": null,
        "identity_namespace": "legacy_unscoped",
        "occurrence_id": null,
        "original_uid": "_cor36ohn6kq68or5clh38oj675h3id366crm6db571j38cr1c4og",
        "canonical_uid": "f63b754dceeb4bf9b94f37c5e8f43aa1",
        "alias_type": "base32hex",
        "reconciliation_method": "base32hex_roundtrip",
        "verified": true,
        "historical_booking_id": null,
        "created_at": "2026-09-17T20:44:04.270063+00:00"
      },
      {
        "id": 1680,
        "event_id": 1292,
        "calendar_id": null,
        "identity_namespace": "legacy_unscoped",
        "occurrence_id": null,
        "original_uid": "f63b754dceeb4bf9b94f37c5e8f43aa1",
        "canonical_uid": "f63b754dceeb4bf9b94f37c5e8f43aa1",
        "alias_type": "google_uid",
        "reconciliation_method": "identity",
        "verified": true,
        "historical_booking_id": null,
        "created_at": "2026-09-17T20:44:04.270063+00:00"
      }
    ],
    "google_evidence": {
      "id": "_cor36ohn6kq68or5clh38oj675h3id366crm6db571j38cr1c4og",
      "summary": "9 pranzo Tuscan escape",
      "status": "confirmed",
      "start": "2026-10-05T13:15:00+02:00",
      "recurring_event_id": null,
      "original_start_time": null,
      "organizer": "calendario.fattoria@gmail.com"
    }
  },
  {
    "before": {
      "id": 2143,
      "customer_name": "Tuscan Escape",
      "experience_name": "Tuscan Escape - Blocco data",
      "booking_date": "2026-10-08",
      "pax": 1,
      "total_amount": 0,
      "customer_payment_status": "pending",
      "supplier_payment_status": "pending",
      "created_at": "2026-09-14T18:18:25.422928+00:00",
      "booking_source": "Tuscan Escape",
      "booking_reference": "GCAL-_6srjeopickr6acpkcpj38d1i70s6ceb369i6adr5cdijcp3",
      "booking_created_at": "2026-09-14",
      "booking_time": "13:15",
      "adults": 1,
      "children": 0,
      "total_people": 1,
      "customer_phone": null,
      "customer_email": null,
      "notes": "Tuscan escape",
      "channel_id": 7,
      "experience_id": 22,
      "supplier_id": 3,
      "your_unit_price": 0,
      "public_unit_price": 0,
      "supplier_unit_cost": 0,
      "total_to_you": 0,
      "total_customer": 0,
      "total_supplier_cost": 0,
      "margin_total": 0,
      "is_cancelled": false,
      "cancelled_at": null,
      "supplier_amount_paid": 0,
      "infants": 0,
      "updated_at": "2026-09-14T18:18:25.422928+00:00",
      "was_modified": false,
      "recovery_tag": null,
      "business_unit_id": 1,
      "non_paying_adults": 0,
      "bokun_booking_reference": null,
      "total_to_you_source": null,
      "agreed_unit_price": null
    },
    "after": {
      "id": 2143,
      "customer_name": "Tuscan Escape",
      "experience_name": "Tour della Cinta Senese con pranzo",
      "booking_date": "2026-10-08",
      "pax": 8,
      "total_amount": 0,
      "customer_payment_status": "pending",
      "supplier_payment_status": "pending",
      "created_at": "2026-09-14T18:18:25.422928+00:00",
      "booking_source": "Tuscan Escape",
      "booking_reference": "GCAL-_6srjeopickr6acpkcpj38d1i70s6ceb369i6adr5cdijcp3",
      "booking_created_at": "2026-09-14",
      "booking_time": "13:15",
      "adults": 8,
      "children": 0,
      "total_people": 9,
      "customer_phone": null,
      "customer_email": null,
      "notes": "9 pranzo Tuscan escape",
      "channel_id": 7,
      "experience_id": 7,
      "supplier_id": 3,
      "your_unit_price": 0,
      "public_unit_price": 0,
      "supplier_unit_cost": 0,
      "total_to_you": 0,
      "total_customer": 0,
      "total_supplier_cost": 0,
      "margin_total": 0,
      "is_cancelled": false,
      "cancelled_at": null,
      "supplier_amount_paid": 0,
      "infants": 0,
      "updated_at": "2026-09-14T18:18:25.422928+00:00",
      "was_modified": true,
      "recovery_tag": null,
      "business_unit_id": 1,
      "non_paying_adults": 1,
      "bokun_booking_reference": null,
      "total_to_you_source": null,
      "agreed_unit_price": null
    },
    "staging": {
      "id": 614,
      "booking_date": "2026-10-08",
      "booking_time": "13:15:00",
      "booking_reference": "GCAL-_6srjeopickr6acpkcpj38d1i70s6ceb369i6adr5cdijcp3",
      "customer_name": "Tuscan",
      "adults": 8,
      "children": 0,
      "infants": 0,
      "experience_id": 7,
      "channel_id": 7,
      "booking_source": "Tuscan Escape",
      "notes": "9 pranzo Tuscan escape",
      "gcal_uid": "_6srjeopickr6acpkcpj38d1i70s6ceb369i6adr5cdijcp336krg",
      "original_title": "9 pranzo Tuscan escape",
      "import_status": "needs_review",
      "imported_booking_id": 2143,
      "created_at": "2026-09-14T16:13:41.627425+00:00",
      "import_origin": "make",
      "gcal_updated_at": "2026-10-08T04:20:00+00:00",
      "gcal_html_link": "https://www.google.com/calendar/event?eid=XzZzcmplb3BpY2tyNmFjcGtjcGozOGQxaTcwczZjZWIzNjlpNmFkcjVjZGlqY3AzMzZrcmcgY2FsZW5kYXJpby5mYXR0b3JpYUBt"
    },
    "canonical_before": {
      "id": 1293,
      "calendar_id": null,
      "identity_namespace": "legacy_unscoped",
      "canonical_uid": "777c2e6e34ff44288f9c2de7ece6dc57",
      "original_uid": "_6srjeopickr6acpkcpj38d1i70s6ceb369i6adr5cdijcp336krg",
      "uid_kind": "google",
      "uid_semantics": "legacy_unknown",
      "occurrence_id": null,
      "gcal_event_id": null,
      "gcal_ical_uid": null,
      "recurring_event_id": null,
      "original_start_at": null,
      "original_start_date": null,
      "original_start_timezone": null,
      "event_date": "2026-10-08",
      "event_time": "13:15:00",
      "original_title": "Tuscan escape",
      "gcal_html_link": "https://www.google.com/calendar/event?eid=XzZzcmplb3BpY2tyNmFjcGtjcGozOGQxaTcwczZjZWIzNjlpNmFkcjVjZGlqY3AzMzZrcmcgY2FsZW5kYXJpby5mYXR0b3JpYUBt",
      "gcal_event_status": "unknown",
      "gcal_updated_at": "2026-09-14T16:05:34+00:00",
      "gcal_received_at": null,
      "historical_booking_id": null,
      "staging_id": 614,
      "historical_source": null,
      "historical_snapshot_at": null,
      "historical_total_guests": null,
      "observed_total_guests": null,
      "effective_total_guests": null,
      "attendance_source": "unknown",
      "attendance_quality": "unknown",
      "attendance_parser_version": "gcal-attendance-review-v1",
      "event_classification": "operational_block",
      "exclusion_reason": "explicit_tuscan_escape_block",
      "last_observation_source": "google_calendar",
      "created_at": "2026-09-17T20:44:04.270063+00:00",
      "updated_at": "2026-09-17T20:44:04.270063+00:00",
      "gcal_observation_verified": false
    },
    "canonical_after": {
      "id": 1293,
      "calendar_id": null,
      "identity_namespace": "legacy_unscoped",
      "canonical_uid": "777c2e6e34ff44288f9c2de7ece6dc57",
      "original_uid": "_6srjeopickr6acpkcpj38d1i70s6ceb369i6adr5cdijcp336krg",
      "uid_kind": "google",
      "uid_semantics": "legacy_unknown",
      "occurrence_id": null,
      "gcal_event_id": null,
      "gcal_ical_uid": null,
      "recurring_event_id": null,
      "original_start_at": null,
      "original_start_date": null,
      "original_start_timezone": null,
      "event_date": "2026-10-08",
      "event_time": "13:15:00",
      "original_title": "9 pranzo Tuscan escape",
      "gcal_html_link": "https://www.google.com/calendar/event?eid=XzZzcmplb3BpY2tyNmFjcGtjcGozOGQxaTcwczZjZWIzNjlpNmFkcjVjZGlqY3AzMzZrcmcgY2FsZW5kYXJpby5mYXR0b3JpYUBt",
      "gcal_event_status": "confirmed",
      "gcal_updated_at": "2026-09-14T16:05:34+00:00",
      "gcal_received_at": null,
      "historical_booking_id": null,
      "staging_id": 614,
      "historical_source": null,
      "historical_snapshot_at": null,
      "historical_total_guests": null,
      "observed_total_guests": 9,
      "effective_total_guests": 8,
      "attendance_source": "google_title",
      "attendance_quality": "parsed",
      "attendance_parser_version": "farm-attendance-v1+manual-review-20261009",
      "event_classification": "customer_event",
      "exclusion_reason": null,
      "last_observation_source": "google_calendar",
      "created_at": "2026-09-17T20:44:04.270063+00:00",
      "updated_at": "2026-09-17T20:44:04.270063+00:00",
      "gcal_observation_verified": false
    },
    "aliases": [
      {
        "id": 1681,
        "event_id": 1293,
        "calendar_id": null,
        "identity_namespace": "legacy_unscoped",
        "occurrence_id": null,
        "original_uid": "_6srjeopickr6acpkcpj38d1i70s6ceb369i6adr5cdijcp336krg",
        "canonical_uid": "777c2e6e34ff44288f9c2de7ece6dc57",
        "alias_type": "base32hex",
        "reconciliation_method": "base32hex_roundtrip",
        "verified": true,
        "historical_booking_id": null,
        "created_at": "2026-09-17T20:44:04.270063+00:00"
      },
      {
        "id": 1682,
        "event_id": 1293,
        "calendar_id": null,
        "identity_namespace": "legacy_unscoped",
        "occurrence_id": null,
        "original_uid": "777c2e6e34ff44288f9c2de7ece6dc57",
        "canonical_uid": "777c2e6e34ff44288f9c2de7ece6dc57",
        "alias_type": "google_uid",
        "reconciliation_method": "identity",
        "verified": true,
        "historical_booking_id": null,
        "created_at": "2026-09-17T20:44:04.270063+00:00"
      }
    ],
    "google_evidence": {
      "id": "_6srjeopickr6acpkcpj38d1i70s6ceb369i6adr5cdijcp336krg",
      "summary": "9 pranzo Tuscan escape",
      "status": "confirmed",
      "start": "2026-10-08T13:15:00+02:00",
      "recurring_event_id": null,
      "original_start_time": null,
      "organizer": "calendario.fattoria@gmail.com"
    }
  },
  {
    "before": {
      "id": 2142,
      "customer_name": "Tuscan Escape",
      "experience_name": "Tuscan Escape - Blocco data",
      "booking_date": "2026-10-09",
      "pax": 1,
      "total_amount": 0,
      "customer_payment_status": "pending",
      "supplier_payment_status": "pending",
      "created_at": "2026-09-14T18:18:13.502239+00:00",
      "booking_source": "Tuscan Escape",
      "booking_reference": "GCAL-_cosjapb6chgm6cpi6or38e1g6tgjgoj2cdi3cp1hc8oj4eb",
      "booking_created_at": "2026-09-14",
      "booking_time": "13:15",
      "adults": 1,
      "children": 0,
      "total_people": 1,
      "customer_phone": null,
      "customer_email": null,
      "notes": "Tuscan escape",
      "channel_id": 7,
      "experience_id": 22,
      "supplier_id": 3,
      "your_unit_price": 0,
      "public_unit_price": 0,
      "supplier_unit_cost": 0,
      "total_to_you": 0,
      "total_customer": 0,
      "total_supplier_cost": 0,
      "margin_total": 0,
      "is_cancelled": false,
      "cancelled_at": null,
      "supplier_amount_paid": 0,
      "infants": 0,
      "updated_at": "2026-09-14T18:18:13.502239+00:00",
      "was_modified": false,
      "recovery_tag": null,
      "business_unit_id": 1,
      "non_paying_adults": 0,
      "bokun_booking_reference": null,
      "total_to_you_source": null,
      "agreed_unit_price": null
    },
    "after": {
      "id": 2142,
      "customer_name": "Tuscan Escape",
      "experience_name": "Tour della Cinta Senese con pranzo",
      "booking_date": "2026-10-09",
      "pax": 5,
      "total_amount": 0,
      "customer_payment_status": "pending",
      "supplier_payment_status": "pending",
      "created_at": "2026-09-14T18:18:13.502239+00:00",
      "booking_source": "Tuscan Escape",
      "booking_reference": "GCAL-_cosjapb6chgm6cpi6or38e1g6tgjgoj2cdi3cp1hc8oj4eb",
      "booking_created_at": "2026-09-14",
      "booking_time": "13:15",
      "adults": 5,
      "children": 0,
      "total_people": 6,
      "customer_phone": null,
      "customer_email": null,
      "notes": "6 pranzo Tuscan escape",
      "channel_id": 7,
      "experience_id": 7,
      "supplier_id": 3,
      "your_unit_price": 0,
      "public_unit_price": 0,
      "supplier_unit_cost": 0,
      "total_to_you": 0,
      "total_customer": 0,
      "total_supplier_cost": 0,
      "margin_total": 0,
      "is_cancelled": false,
      "cancelled_at": null,
      "supplier_amount_paid": 0,
      "infants": 0,
      "updated_at": "2026-09-14T18:18:13.502239+00:00",
      "was_modified": true,
      "recovery_tag": null,
      "business_unit_id": 1,
      "non_paying_adults": 1,
      "bokun_booking_reference": null,
      "total_to_you_source": null,
      "agreed_unit_price": null
    },
    "staging": {
      "id": 615,
      "booking_date": "2026-10-09",
      "booking_time": "13:15:00",
      "booking_reference": "GCAL-_cosjapb6chgm6cpi6or38e1g6tgjgoj2cdi3cp1hc8oj4eb",
      "customer_name": "Tuscan",
      "adults": 5,
      "children": 0,
      "infants": 0,
      "experience_id": 7,
      "channel_id": 7,
      "booking_source": "Tuscan Escape",
      "notes": "6 pranzo Tuscan escape",
      "gcal_uid": "_cosjapb6chgm6cpi6or38e1g6tgjgoj2cdi3cp1hc8oj4eb36srg",
      "original_title": "6 pranzo Tuscan escape",
      "import_status": "needs_review",
      "imported_booking_id": 2142,
      "created_at": "2026-09-14T16:13:42.518159+00:00",
      "import_origin": "make",
      "gcal_updated_at": "2026-10-08T16:27:35+00:00",
      "gcal_html_link": "https://www.google.com/calendar/event?eid=X2Nvc2phcGI2Y2hnbTZjcGk2b3IzOGUxZzZ0Z2pnb2oyY2RpM2NwMWhjOG9qNGViMzZzcmcgY2FsZW5kYXJpby5mYXR0b3JpYUBt"
    },
    "canonical_before": {
      "id": 1294,
      "calendar_id": null,
      "identity_namespace": "legacy_unscoped",
      "canonical_uid": "f95efdac32664807a8bbcd6d1b129c77",
      "original_uid": "_cosjapb6chgm6cpi6or38e1g6tgjgoj2cdi3cp1hc8oj4eb36srg",
      "uid_kind": "google",
      "uid_semantics": "legacy_unknown",
      "occurrence_id": null,
      "gcal_event_id": null,
      "gcal_ical_uid": null,
      "recurring_event_id": null,
      "original_start_at": null,
      "original_start_date": null,
      "original_start_timezone": null,
      "event_date": "2026-10-09",
      "event_time": "13:15:00",
      "original_title": "Tuscan escape",
      "gcal_html_link": "https://www.google.com/calendar/event?eid=X2Nvc2phcGI2Y2hnbTZjcGk2b3IzOGUxZzZ0Z2pnb2oyY2RpM2NwMWhjOG9qNGViMzZzcmcgY2FsZW5kYXJpby5mYXR0b3JpYUBt",
      "gcal_event_status": "unknown",
      "gcal_updated_at": "2026-09-14T16:05:48+00:00",
      "gcal_received_at": null,
      "historical_booking_id": null,
      "staging_id": 615,
      "historical_source": null,
      "historical_snapshot_at": null,
      "historical_total_guests": null,
      "observed_total_guests": null,
      "effective_total_guests": null,
      "attendance_source": "unknown",
      "attendance_quality": "unknown",
      "attendance_parser_version": "gcal-attendance-review-v1",
      "event_classification": "operational_block",
      "exclusion_reason": "explicit_tuscan_escape_block",
      "last_observation_source": "google_calendar",
      "created_at": "2026-09-17T20:44:04.270063+00:00",
      "updated_at": "2026-09-17T20:44:04.270063+00:00",
      "gcal_observation_verified": false
    },
    "canonical_after": {
      "id": 1294,
      "calendar_id": null,
      "identity_namespace": "legacy_unscoped",
      "canonical_uid": "f95efdac32664807a8bbcd6d1b129c77",
      "original_uid": "_cosjapb6chgm6cpi6or38e1g6tgjgoj2cdi3cp1hc8oj4eb36srg",
      "uid_kind": "google",
      "uid_semantics": "legacy_unknown",
      "occurrence_id": null,
      "gcal_event_id": null,
      "gcal_ical_uid": null,
      "recurring_event_id": null,
      "original_start_at": null,
      "original_start_date": null,
      "original_start_timezone": null,
      "event_date": "2026-10-09",
      "event_time": "13:15:00",
      "original_title": "6 pranzo Tuscan escape",
      "gcal_html_link": "https://www.google.com/calendar/event?eid=X2Nvc2phcGI2Y2hnbTZjcGk2b3IzOGUxZzZ0Z2pnb2oyY2RpM2NwMWhjOG9qNGViMzZzcmcgY2FsZW5kYXJpby5mYXR0b3JpYUBt",
      "gcal_event_status": "confirmed",
      "gcal_updated_at": "2026-09-14T16:05:48+00:00",
      "gcal_received_at": null,
      "historical_booking_id": null,
      "staging_id": 615,
      "historical_source": null,
      "historical_snapshot_at": null,
      "historical_total_guests": null,
      "observed_total_guests": 6,
      "effective_total_guests": 5,
      "attendance_source": "google_title",
      "attendance_quality": "parsed",
      "attendance_parser_version": "farm-attendance-v1+manual-review-20261009",
      "event_classification": "customer_event",
      "exclusion_reason": null,
      "last_observation_source": "google_calendar",
      "created_at": "2026-09-17T20:44:04.270063+00:00",
      "updated_at": "2026-09-17T20:44:04.270063+00:00",
      "gcal_observation_verified": false
    },
    "aliases": [
      {
        "id": 1683,
        "event_id": 1294,
        "calendar_id": null,
        "identity_namespace": "legacy_unscoped",
        "occurrence_id": null,
        "original_uid": "_cosjapb6chgm6cpi6or38e1g6tgjgoj2cdi3cp1hc8oj4eb36srg",
        "canonical_uid": "f95efdac32664807a8bbcd6d1b129c77",
        "alias_type": "base32hex",
        "reconciliation_method": "base32hex_roundtrip",
        "verified": true,
        "historical_booking_id": null,
        "created_at": "2026-09-17T20:44:04.270063+00:00"
      },
      {
        "id": 1684,
        "event_id": 1294,
        "calendar_id": null,
        "identity_namespace": "legacy_unscoped",
        "occurrence_id": null,
        "original_uid": "f95efdac32664807a8bbcd6d1b129c77",
        "canonical_uid": "f95efdac32664807a8bbcd6d1b129c77",
        "alias_type": "google_uid",
        "reconciliation_method": "identity",
        "verified": true,
        "historical_booking_id": null,
        "created_at": "2026-09-17T20:44:04.270063+00:00"
      }
    ],
    "google_evidence": {
      "id": "_cosjapb6chgm6cpi6or38e1g6tgjgoj2cdi3cp1hc8oj4eb36srg",
      "summary": "6 pranzo Tuscan escape",
      "status": "confirmed",
      "start": "2026-10-09T13:15:00+02:00",
      "recurring_event_id": null,
      "original_start_time": null,
      "organizer": "calendario.fattoria@gmail.com"
    }
  },
  {
    "before": {
      "id": 2141,
      "customer_name": "Tuscan Escape",
      "experience_name": "Tuscan Escape - Blocco data",
      "booking_date": "2026-10-11",
      "pax": 1,
      "total_amount": 0,
      "customer_payment_status": "pending",
      "supplier_payment_status": "pending",
      "created_at": "2026-09-14T18:17:56.332714+00:00",
      "booking_source": "Tuscan Escape",
      "booking_reference": "GCAL-_64ojcopmckpm4c3469i38chlc9gjed1ockq3cob36ks30p9",
      "booking_created_at": "2026-09-14",
      "booking_time": "13:15",
      "adults": 1,
      "children": 0,
      "total_people": 1,
      "customer_phone": null,
      "customer_email": null,
      "notes": "Tuscan escape",
      "channel_id": 7,
      "experience_id": 22,
      "supplier_id": 3,
      "your_unit_price": 0,
      "public_unit_price": 0,
      "supplier_unit_cost": 0,
      "total_to_you": 0,
      "total_customer": 0,
      "total_supplier_cost": 0,
      "margin_total": 0,
      "is_cancelled": false,
      "cancelled_at": null,
      "supplier_amount_paid": 0,
      "infants": 0,
      "updated_at": "2026-09-14T18:17:56.332714+00:00",
      "was_modified": false,
      "recovery_tag": null,
      "business_unit_id": 1,
      "non_paying_adults": 0,
      "bokun_booking_reference": null,
      "total_to_you_source": null,
      "agreed_unit_price": null
    },
    "after": {
      "id": 2141,
      "customer_name": "Tuscan Escape",
      "experience_name": "Tour della Cinta Senese con pranzo",
      "booking_date": "2026-10-11",
      "pax": 7,
      "total_amount": 0,
      "customer_payment_status": "pending",
      "supplier_payment_status": "pending",
      "created_at": "2026-09-14T18:17:56.332714+00:00",
      "booking_source": "Tuscan Escape",
      "booking_reference": "GCAL-_64ojcopmckpm4c3469i38chlc9gjed1ockq3cob36ks30p9",
      "booking_created_at": "2026-09-14",
      "booking_time": "13:15",
      "adults": 7,
      "children": 0,
      "total_people": 8,
      "customer_phone": null,
      "customer_email": null,
      "notes": "8 pranzo Tuscan escape",
      "channel_id": 7,
      "experience_id": 7,
      "supplier_id": 3,
      "your_unit_price": 0,
      "public_unit_price": 0,
      "supplier_unit_cost": 0,
      "total_to_you": 0,
      "total_customer": 0,
      "total_supplier_cost": 0,
      "margin_total": 0,
      "is_cancelled": false,
      "cancelled_at": null,
      "supplier_amount_paid": 0,
      "infants": 0,
      "updated_at": "2026-09-14T18:17:56.332714+00:00",
      "was_modified": true,
      "recovery_tag": null,
      "business_unit_id": 1,
      "non_paying_adults": 1,
      "bokun_booking_reference": null,
      "total_to_you_source": null,
      "agreed_unit_price": null
    },
    "staging": {
      "id": 616,
      "booking_date": "2026-10-11",
      "booking_time": "13:15:00",
      "booking_reference": "GCAL-_64ojcopmckpm4c3469i38chlc9gjed1ockq3cob36ks30p9",
      "customer_name": "Tuscan",
      "adults": 7,
      "children": 0,
      "infants": 0,
      "experience_id": 7,
      "channel_id": 7,
      "booking_source": "Tuscan Escape",
      "notes": "8 pranzo Tuscan escape",
      "gcal_uid": "_64ojcopmckpm4c3469i38chlc9gjed1ockq3cob36ks30p9jccog",
      "original_title": "8 pranzo Tuscan escape",
      "import_status": "needs_review",
      "imported_booking_id": 2141,
      "created_at": "2026-09-14T16:13:43.467821+00:00",
      "import_origin": "make",
      "gcal_updated_at": "2026-10-04T15:44:46+00:00",
      "gcal_html_link": "https://www.google.com/calendar/event?eid=XzY0b2pjb3BtY2twbTRjMzQ2OWkzOGNobGM5Z2plZDFvY2txM2NvYjM2a3MzMHA5amNjb2cgY2FsZW5kYXJpby5mYXR0b3JpYUBt"
    },
    "canonical_before": {
      "id": 1295,
      "calendar_id": null,
      "identity_namespace": "legacy_unscoped",
      "canonical_uid": "116c6e3b0d2d425ba748e46ac580e3c1",
      "original_uid": "_64ojcopmckpm4c3469i38chlc9gjed1ockq3cob36ks30p9jccog",
      "uid_kind": "google",
      "uid_semantics": "legacy_unknown",
      "occurrence_id": null,
      "gcal_event_id": null,
      "gcal_ical_uid": null,
      "recurring_event_id": null,
      "original_start_at": null,
      "original_start_date": null,
      "original_start_timezone": null,
      "event_date": "2026-10-11",
      "event_time": "13:15:00",
      "original_title": "Tuscan escape",
      "gcal_html_link": "https://www.google.com/calendar/event?eid=XzY0b2pjb3BtY2twbTRjMzQ2OWkzOGNobGM5Z2plZDFvY2txM2NvYjM2a3MzMHA5amNjb2cgY2FsZW5kYXJpby5mYXR0b3JpYUBt",
      "gcal_event_status": "unknown",
      "gcal_updated_at": "2026-09-14T16:05:58+00:00",
      "gcal_received_at": null,
      "historical_booking_id": null,
      "staging_id": 616,
      "historical_source": null,
      "historical_snapshot_at": null,
      "historical_total_guests": null,
      "observed_total_guests": null,
      "effective_total_guests": null,
      "attendance_source": "unknown",
      "attendance_quality": "unknown",
      "attendance_parser_version": "gcal-attendance-review-v1",
      "event_classification": "operational_block",
      "exclusion_reason": "explicit_tuscan_escape_block",
      "last_observation_source": "google_calendar",
      "created_at": "2026-09-17T20:44:04.270063+00:00",
      "updated_at": "2026-09-17T20:44:04.270063+00:00",
      "gcal_observation_verified": false
    },
    "canonical_after": {
      "id": 1295,
      "calendar_id": null,
      "identity_namespace": "legacy_unscoped",
      "canonical_uid": "116c6e3b0d2d425ba748e46ac580e3c1",
      "original_uid": "_64ojcopmckpm4c3469i38chlc9gjed1ockq3cob36ks30p9jccog",
      "uid_kind": "google",
      "uid_semantics": "legacy_unknown",
      "occurrence_id": null,
      "gcal_event_id": null,
      "gcal_ical_uid": null,
      "recurring_event_id": null,
      "original_start_at": null,
      "original_start_date": null,
      "original_start_timezone": null,
      "event_date": "2026-10-11",
      "event_time": "13:15:00",
      "original_title": "8 pranzo Tuscan escape",
      "gcal_html_link": "https://www.google.com/calendar/event?eid=XzY0b2pjb3BtY2twbTRjMzQ2OWkzOGNobGM5Z2plZDFvY2txM2NvYjM2a3MzMHA5amNjb2cgY2FsZW5kYXJpby5mYXR0b3JpYUBt",
      "gcal_event_status": "confirmed",
      "gcal_updated_at": "2026-09-14T16:05:58+00:00",
      "gcal_received_at": null,
      "historical_booking_id": null,
      "staging_id": 616,
      "historical_source": null,
      "historical_snapshot_at": null,
      "historical_total_guests": null,
      "observed_total_guests": 8,
      "effective_total_guests": 7,
      "attendance_source": "google_title",
      "attendance_quality": "parsed",
      "attendance_parser_version": "farm-attendance-v1+manual-review-20261009",
      "event_classification": "customer_event",
      "exclusion_reason": null,
      "last_observation_source": "google_calendar",
      "created_at": "2026-09-17T20:44:04.270063+00:00",
      "updated_at": "2026-09-17T20:44:04.270063+00:00",
      "gcal_observation_verified": false
    },
    "aliases": [
      {
        "id": 1685,
        "event_id": 1295,
        "calendar_id": null,
        "identity_namespace": "legacy_unscoped",
        "occurrence_id": null,
        "original_uid": "_64ojcopmckpm4c3469i38chlc9gjed1ockq3cob36ks30p9jccog",
        "canonical_uid": "116c6e3b0d2d425ba748e46ac580e3c1",
        "alias_type": "base32hex",
        "reconciliation_method": "base32hex_roundtrip",
        "verified": true,
        "historical_booking_id": null,
        "created_at": "2026-09-17T20:44:04.270063+00:00"
      },
      {
        "id": 1686,
        "event_id": 1295,
        "calendar_id": null,
        "identity_namespace": "legacy_unscoped",
        "occurrence_id": null,
        "original_uid": "116c6e3b0d2d425ba748e46ac580e3c1",
        "canonical_uid": "116c6e3b0d2d425ba748e46ac580e3c1",
        "alias_type": "google_uid",
        "reconciliation_method": "identity",
        "verified": true,
        "historical_booking_id": null,
        "created_at": "2026-09-17T20:44:04.270063+00:00"
      }
    ],
    "google_evidence": {
      "id": "_64ojcopmckpm4c3469i38chlc9gjed1ockq3cob36ks30p9jccog",
      "summary": "8 pranzo Tuscan escape",
      "status": "confirmed",
      "start": "2026-10-11T13:15:00+02:00",
      "recurring_event_id": null,
      "original_start_time": null,
      "organizer": "calendario.fattoria@gmail.com"
    }
  },
  {
    "before": {
      "id": 2190,
      "customer_name": "Tuscan Escape",
      "experience_name": "Tuscan Escape - Blocco data",
      "booking_date": "2026-10-22",
      "pax": 1,
      "total_amount": 0,
      "customer_payment_status": "pending",
      "supplier_payment_status": "pending",
      "created_at": "2026-09-20T16:53:21.92565+00:00",
      "booking_source": "Tuscan Escape",
      "booking_reference": "GCAL-_60pjepb6ckoj4dph61i38pj565gm2d336ti64cpi6phm4e1",
      "booking_created_at": "2026-09-20",
      "booking_time": "13:15",
      "adults": 1,
      "children": 0,
      "total_people": 1,
      "customer_phone": null,
      "customer_email": null,
      "notes": "Tuscan escape",
      "channel_id": 7,
      "experience_id": 22,
      "supplier_id": 3,
      "your_unit_price": 0,
      "public_unit_price": 0,
      "supplier_unit_cost": 0,
      "total_to_you": 0,
      "total_customer": 0,
      "total_supplier_cost": 0,
      "margin_total": 0,
      "is_cancelled": false,
      "cancelled_at": null,
      "supplier_amount_paid": 0,
      "infants": 0,
      "updated_at": "2026-09-20T16:53:21.92565+00:00",
      "was_modified": false,
      "recovery_tag": null,
      "business_unit_id": 1,
      "non_paying_adults": 0,
      "bokun_booking_reference": null,
      "total_to_you_source": null,
      "agreed_unit_price": null
    },
    "after": {
      "id": 2190,
      "customer_name": "Tuscan Escape",
      "experience_name": "Tour della Cinta Senese con pranzo",
      "booking_date": "2026-10-22",
      "pax": 7,
      "total_amount": 0,
      "customer_payment_status": "pending",
      "supplier_payment_status": "pending",
      "created_at": "2026-09-20T16:53:21.92565+00:00",
      "booking_source": "Tuscan Escape",
      "booking_reference": "GCAL-_60pjepb6ckoj4dph61i38pj565gm2d336ti64cpi6phm4e1",
      "booking_created_at": "2026-09-20",
      "booking_time": "13:15",
      "adults": 7,
      "children": 0,
      "total_people": 8,
      "customer_phone": null,
      "customer_email": null,
      "notes": "8 pranzo Tuscan escape",
      "channel_id": 7,
      "experience_id": 7,
      "supplier_id": 3,
      "your_unit_price": 0,
      "public_unit_price": 0,
      "supplier_unit_cost": 0,
      "total_to_you": 0,
      "total_customer": 0,
      "total_supplier_cost": 0,
      "margin_total": 0,
      "is_cancelled": false,
      "cancelled_at": null,
      "supplier_amount_paid": 0,
      "infants": 0,
      "updated_at": "2026-09-20T16:53:21.92565+00:00",
      "was_modified": true,
      "recovery_tag": null,
      "business_unit_id": 1,
      "non_paying_adults": 1,
      "bokun_booking_reference": null,
      "total_to_you_source": null,
      "agreed_unit_price": null
    },
    "staging": {
      "id": 638,
      "booking_date": "2026-10-22",
      "booking_time": "13:15:00",
      "booking_reference": "GCAL-_60pjepb6ckoj4dph61i38pj565gm2d336ti64cpi6phm4e1",
      "customer_name": "Tuscan",
      "adults": 7,
      "children": 0,
      "infants": 0,
      "experience_id": 7,
      "channel_id": 7,
      "booking_source": "Tuscan Escape",
      "notes": "8 pranzo Tuscan escape",
      "gcal_uid": "_60pjepb6ckoj4dph61i38pj565gm2d336ti64cpi6phm4e1l69i0",
      "original_title": "8 pranzo Tuscan escape",
      "import_status": "needs_review",
      "imported_booking_id": 2190,
      "created_at": "2026-09-19T17:44:33.888865+00:00",
      "import_origin": "make",
      "gcal_updated_at": "2026-10-06T18:33:02+00:00",
      "gcal_html_link": "https://www.google.com/calendar/event?eid=XzYwcGplcGI2Y2tvajRkcGg2MWkzOHBqNTY1Z20yZDMzNnRpNjRjcGk2cGhtNGUxbDY5aTAgY2FsZW5kYXJpby5mYXR0b3JpYUBt"
    },
    "canonical_before": {
      "id": 1322,
      "calendar_id": null,
      "identity_namespace": "legacy_unscoped",
      "canonical_uid": "037efe12710d4fe1aa4c7db326cb852d",
      "original_uid": "_60pjepb6ckoj4dph61i38pj565gm2d336ti64cpi6phm4e1l69i0",
      "uid_kind": "google",
      "uid_semantics": "event_id",
      "occurrence_id": null,
      "gcal_event_id": "_60pjepb6ckoj4dph61i38pj565gm2d336ti64cpi6phm4e1l69i0",
      "gcal_ical_uid": null,
      "recurring_event_id": null,
      "original_start_at": null,
      "original_start_date": null,
      "original_start_timezone": null,
      "event_date": "2026-10-22",
      "event_time": "13:15:00",
      "original_title": "8 pranzo Tuscan escape",
      "gcal_html_link": null,
      "gcal_event_status": "confirmed",
      "gcal_updated_at": "2026-10-06T18:33:02+00:00",
      "gcal_received_at": "2026-10-06T18:44:31.721+00:00",
      "historical_booking_id": null,
      "staging_id": null,
      "historical_source": null,
      "historical_snapshot_at": null,
      "historical_total_guests": null,
      "observed_total_guests": 8,
      "effective_total_guests": 7,
      "attendance_source": "google_title",
      "attendance_quality": "parsed",
      "attendance_parser_version": "farm-attendance-v1",
      "event_classification": "customer_event",
      "exclusion_reason": null,
      "last_observation_source": "google_calendar",
      "created_at": "2026-10-06T18:44:36.731987+00:00",
      "updated_at": "2026-10-06T18:44:31.721+00:00",
      "gcal_observation_verified": true
    },
    "canonical_after": {
      "id": 1322,
      "calendar_id": null,
      "identity_namespace": "legacy_unscoped",
      "canonical_uid": "037efe12710d4fe1aa4c7db326cb852d",
      "original_uid": "_60pjepb6ckoj4dph61i38pj565gm2d336ti64cpi6phm4e1l69i0",
      "uid_kind": "google",
      "uid_semantics": "event_id",
      "occurrence_id": null,
      "gcal_event_id": "_60pjepb6ckoj4dph61i38pj565gm2d336ti64cpi6phm4e1l69i0",
      "gcal_ical_uid": null,
      "recurring_event_id": null,
      "original_start_at": null,
      "original_start_date": null,
      "original_start_timezone": null,
      "event_date": "2026-10-22",
      "event_time": "13:15:00",
      "original_title": "8 pranzo Tuscan escape",
      "gcal_html_link": null,
      "gcal_event_status": "confirmed",
      "gcal_updated_at": "2026-10-06T18:33:02+00:00",
      "gcal_received_at": "2026-10-06T18:44:31.721+00:00",
      "historical_booking_id": null,
      "staging_id": null,
      "historical_source": null,
      "historical_snapshot_at": null,
      "historical_total_guests": null,
      "observed_total_guests": 8,
      "effective_total_guests": 7,
      "attendance_source": "google_title",
      "attendance_quality": "parsed",
      "attendance_parser_version": "farm-attendance-v1",
      "event_classification": "customer_event",
      "exclusion_reason": null,
      "last_observation_source": "google_calendar",
      "created_at": "2026-10-06T18:44:36.731987+00:00",
      "updated_at": "2026-10-06T18:44:31.721+00:00",
      "gcal_observation_verified": true
    },
    "aliases": [],
    "google_evidence": {
      "id": "_60pjepb6ckoj4dph61i38pj565gm2d336ti64cpi6phm4e1l69i0",
      "summary": "8 pranzo Tuscan escape",
      "status": "confirmed",
      "start": "2026-10-22T13:15:00+02:00",
      "recurring_event_id": null,
      "original_start_time": null,
      "organizer": "calendario.fattoria@gmail.com"
    }
  }
]'::jsonb;
  t jsonb; b jsonb; e jsonb; s jsonb; before_b jsonb; after_b jsonb; before_e jsonb; after_e jsonb;
  changed integer;
begin
  lock table public.bookings, public.google_calendar_import_staging,
    public.google_calendar_events, public.google_calendar_event_aliases,
    public.fmdq_monthly_invoices, public.experiences in share row exclusive mode;
  if exists (select 1 from pg_trigger where tgrelid in ('public.bookings'::regclass,'public.google_calendar_events'::regclass)
    and not tgisinternal and tgenabled <> 'D' and (tgtype::integer & 16) <> 0)
    or exists (select 1 from pg_rewrite where ev_class in ('public.bookings'::regclass,'public.google_calendar_events'::regclass)
    and ev_type = '2' and ev_enabled <> 'D') then raise exception 'Review UPDATE hooks first'; end if;
  -- Complete preflight before ANY update; fail closed on manual edits, cancellation,
  -- changed title/date/UID, duplicate links, invoice additions, or mixed repair states.
  for t in select value from jsonb_array_elements(targets) loop
    select to_jsonb(row) into b from public.bookings row where id=(t->'before'->>'id')::bigint;
    select to_jsonb(row) into s from public.google_calendar_import_staging row where id=(t->'staging'->>'id')::bigint;
    select to_jsonb(row) into e from public.google_calendar_events row where id=(t->'canonical_before'->>'id')::bigint;
    before_b := to_jsonb(jsonb_populate_record(null::public.bookings,t->'before'));
    after_b := to_jsonb(jsonb_populate_record(null::public.bookings,t->'after'));
    before_e := to_jsonb(jsonb_populate_record(null::public.google_calendar_events,t->'canonical_before'));
    after_e := to_jsonb(jsonb_populate_record(null::public.google_calendar_events,t->'canonical_after'));
    if b is null or e is null or s is distinct from to_jsonb(jsonb_populate_record(null::public.google_calendar_import_staging,t->'staging'))
      or not ((b=before_b and e=before_e) or (b=after_b and e=after_e)) then
      raise exception 'October correction: snapshot/manual/cancellation mismatch for %', t->'before'->>'id';
    end if;
    if (select count(*) from public.bookings where upper(booking_reference)=upper(t->'before'->>'booking_reference')) <> 1
      or exists (select 1 from public.google_calendar_import_staging where id<>(t->'staging'->>'id')::bigint
        and (upper(booking_reference)=upper(t->'staging'->>'booking_reference')
          or imported_booking_id=(t->'before'->>'id')::bigint))
      or exists (select 1 from public.google_calendar_events where id<>(t->'canonical_before'->>'id')::bigint
        and identity_namespace=t->'canonical_before'->>'identity_namespace' and occurrence_id is null
        and (canonical_uid=t->'canonical_before'->>'canonical_uid' or original_uid=t->'staging'->>'gcal_uid'))
      or exists (select 1 from public.fmdq_monthly_invoices where channel_id=7 and invoice_month='2026-10-01')
      or not exists (select 1 from public.experiences where id=7 and name=t->'after'->>'experience_name' and supplier_id=3)
      or (select count(*) from public.google_calendar_event_aliases where event_id=(t->'canonical_before'->>'id')::bigint)
        <> jsonb_array_length(t->'aliases')
      or exists (select 1 from jsonb_array_elements(t->'aliases') a where not exists
        (select 1 from public.google_calendar_event_aliases row where to_jsonb(row)=
          to_jsonb(jsonb_populate_record(null::public.google_calendar_event_aliases,a)))) then
      raise exception 'October correction: identity/invoice/catalog evidence changed for %',t->'before'->>'id';
    end if;
  end loop;
  for t in select value from jsonb_array_elements(targets) loop
    select to_jsonb(row) into b from public.bookings row where id=(t->'before'->>'id')::bigint;
    if b=to_jsonb(jsonb_populate_record(null::public.bookings,t->'after')) then continue; end if;
    update public.bookings set adults=(t->'after'->>'adults')::integer, children=0, infants=0,
      non_paying_adults=1, total_people=(t->'after'->>'total_people')::integer, pax=(t->'after'->>'pax')::integer,
      experience_id=7, experience_name=t->'after'->>'experience_name', notes=t->'after'->>'notes', was_modified=true
      where id=(t->'before'->>'id')::bigint;
    get diagnostics changed = row_count;
    if changed <> 1 then raise exception 'Expected one booking'; end if;
    if t->'canonical_before' is distinct from t->'canonical_after' then
      update public.google_calendar_events set original_title=t->'canonical_after'->>'original_title',
        observed_total_guests=(t->'canonical_after'->>'observed_total_guests')::integer,
        effective_total_guests=(t->'canonical_after'->>'effective_total_guests')::integer,
        attendance_source='google_title', attendance_quality='parsed',
        attendance_parser_version='farm-attendance-v1+manual-review-20261009',
        event_classification='customer_event', exclusion_reason=null, gcal_event_status='confirmed'
        where id=(t->'canonical_before'->>'id')::bigint;
      get diagnostics changed = row_count;
      if changed <> 1 then raise exception 'Expected one canonical'; end if;
    end if;
  end loop;
  for t in select value from jsonb_array_elements(targets) loop
    if (select to_jsonb(row) from public.bookings row where id=(t->'before'->>'id')::bigint)
        is distinct from to_jsonb(jsonb_populate_record(null::public.bookings,t->'after'))
      or (select to_jsonb(row) from public.google_calendar_events row where id=(t->'canonical_before'->>'id')::bigint)
        is distinct from to_jsonb(jsonb_populate_record(null::public.google_calendar_events,t->'canonical_after')) then
      raise exception 'October correction postcondition failed';
    end if;
  end loop;
end;
$correction$;
commit;
